sed -i 's/caseManagement\.db/clinic.db/g' ./CaseManagement.java
sed -i 's/caseManagement\.db/clinic.db/g' ./Router.java
sed -i 's/caseManagement\.db/clinic.db/g' ./views/AppointmentView
sed -i 's/caseManagement\.db/clinic.db/g' ./views/CustomerView.java
sed -i 's/caseManagement\.db/clinic.db/g' ./views/DiseaseView.java
sed -i 's/caseManagement\.db/clinic.db/g' ./views/HomeView.java
sed -i 's/caseManagement\.db/clinic.db/g' ./views/LoginView.java
sed -i 's/caseManagement\.db/clinic.db/g' ./views/LogView.java
sed -i 's/caseManagement\.db/clinic.db/g' ./views/MedicineView.java
sed -i 's/caseManagement\.db/clinic.db/g' ./views/RecordView.java
sed -i 's/caseManagement\.db/clinic.db/g' ./views/UserView.java
sed -i 's/caseManagement\.db/clinic.db/g' ./controllers/AppointmentController.java
sed -i 's/caseManagement\.db/clinic.db/g' ./controllers/CustomerController.java
sed -i 's/caseManagement\.db/clinic.db/g' ./controllers/DiseaseController.java
sed -i 's/caseManagement\.db/clinic.db/g' ./controllers/HomeController.java
sed -i 's/caseManagement\.db/clinic.db/g' ./controllers/LogController.java
sed -i 's/caseManagement\.db/clinic.db/g' ./controllers/MedicineController.java
sed -i 's/caseManagement\.db/clinic.db/g' ./controllers/MedicineToDiseaseController.java
sed -i 's/caseManagement\.db/clinic.db/g' ./controllers/RecordController.java
sed -i 's/caseManagement\.db/clinic.db/g' ./controllers/UserController.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Case.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Contact.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/ContactMethod.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Customer.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Frequency.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Gender.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Log.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/MiscButton.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Priority.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Record.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Role.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/RouterModel.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Severity.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/SubscribeActionListener.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/Subscription.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/SubscriptionToCustomer.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/SubscriptionType.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/UnsubscribeActionListener.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/User.java
sed -i 's/caseManagement\.db/clinic.db/g' ./models/View.java
